name: Upload Large File to GitHub with LFS

on: [push, workflow_dispatch]

jobs:
  upload-large-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          lfs: true # Aktifkan LFS di dalam workflow

      - name: Install Git LFS
        run: |
          git lfs install
          git lfs track "*.zip"

      - name: Download Large File (Contoh)
        run: |
          wget -O big-file.zip https://download2262.mediafire.com/i6l2a57600lgNsbFCO8QznFMt2-Dv4BXH0cIUKfxg9W_3UDgeuhw0n3y96MMpB74wj5PoVhS1_nG4VlpMANsjUiNsyHwT_IBBb30y9wgQOW5Cq5AK4wSo-B3aoV8ML35hJwXKdawYHhtBA2PkimnBGQ3cnnO3u7m9uw91ZvGSeyHCcE/cg5xu2wenneg9wr/Alqanime_MoyAdUncenFull_TanpaTimpahan_1080p.mp4

      - name: Commit & Push File ke Repo
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://nouzen-storage:${GH_PAT}@github.com/nouzen-storage/anime-libs.git

          git add .gitattributes
          git add big-file.zip
          git commit -m "Added large file via GitHub Actions"
          git push origin main
