name: Save Large File to GitHub Artifacts

on: [push, workflow_dispatch] # Jalan tiap push atau manual

jobs:
  save-large-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Download Large File (Contoh)
        run: |
          wget -O big-file.mp4 https://download2282.mediafire.com/umr93pijnd1ge1uVq7KiII0wfuPrvX3CWmcyQR6A1jeTq4j_PH5giGMdDLcZnJjnJ_e_RSJVVElPJri0z5AzVi_-rq_Zi-fN23GSTfEKQH-pcR4Pdkii-RVLAZ9pOdnOmRJ8Uctm2Gkp7ILhJ-kLQeraR8EGzE3drj4g0ooTayo9M9A/cg5xu2wenneg9wr/Alqanime_MoyAdUncenFull_TanpaTimpahan_1080p.mp4

      - name: Upload File to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: large-file
          path: big-file.mp4
          retention-days: 7 # Bisa diakses selama 7 hari
