name: Save Large File to GitHub Artifacts

on: [push, workflow_dispatch] # Jalan tiap push atau manual

jobs:
  save-large-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download Large File (Contoh)
        run: |
          wget -O big-file.rar https://drive.usercontent.google.com/download?id=1uPUrqrBTjte4gscZ0qFVHfDiQmwg5wxz&export=download&authuser=0&confirm=t&uuid=93d88482-4ed5-4e2b-91ad-edff5783eaab&at=AEz70l5GNd0tsc8Kfvesgy1F9Xqf%3A1742855027831

      - name: Upload File to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: large-file
          path: big-file.rar
          retention-days: 7 # Bisa diakses selama 7 hari
